# Generated by Django 3.0.3 on 2021-04-18 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='subexe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20)),
                ('ename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.exe')),
            ],
        ),
        migrations.CreateModel(
            name='trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('exercise', models.CharField(max_length=20)),
                ('tdisc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wname', models.CharField(max_length=20)),
                ('wdisc', models.TextField()),
                ('image', models.ImageField(upload_to='image')),
                ('ename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.exe')),
                ('sname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subexe')),
            ],
        ),
    ]
